apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-collection
  description: A collection of Example Software Templates for Backstage
spec:
  type: url
  targets:
    - templates/spring-boot-basic/template.yaml
    - templates/spring-boot-basic-on-kubernetes/template.yaml
    - templates/spring-boot-basic-on-openshift/template.yaml
    - templates/spring-ai-on-openshift/template.yaml
    - templates/dotnet-basic-on-openshift/template.yaml
    - templates/spring-boot-with-db-on-openshift/template.yaml
    - templates/simple-k8s-apply/template.yaml
