apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.appName }}
spec:
  data:
    - remoteRef:
        key: ${{ values.appName }}/secret-password
      secretKey: db-password
    - remoteRef:
        key: ${{ values.appName }}/secret-user
      secretKey: db-user
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: conjur
  target:
    creationPolicy: Owner
    name: ${{ values.appName }}
