quarkus.langchain4j.mcp.mcp-service.transport-type = http
quarkus.langchain4j.mcp.mcp-service.url = http://localhost:8080/mcp/sse
quarkus.langchain4j.mcp.mcp-service.log-requests = true
quarkus.langchain4j.mcp.mcp-service.log-responses = true

quarkus.langchain4j.chat-model.provider = openai
quarkus.langchain4j.log-requests = true
quarkus.langchain4j.log-responses = true
quarkus.langchain4j.openai.api-key = ${AI_TOKEN}
quarkus.langchain4j.openai.timeout = 20s